/*
CREATE TABLE UF (
                    CODIGO_UF NUMBER GENERATED BY DEFAULT AS IDENTITY,
                    SIGLA VARCHAR2(255),
                    NOME VARCHAR2(255),
                    STATUS NUMBER,
                    PRIMARY KEY (CODIGO_UF)
);
*/

